### ISSUE TITLE
Excluding some markers

### ISSUE THREAD

**Issue by ScreamZ** [JiriHoffmann/react-native-clusterer#2]
I'm backporting the original issue because I think this repository might need it aswell.

https://github.com/venits/react-native-map-clustering/issues/236

**Comment by JiriHoffmann** [comment]
Adding it doesn't make sense. If you don't want markers to be clustered then just keep them in two separate variables, one clustered, one not. Also, you should keep the marker for user location excluded anyways since it should be visually different from all other markers and you wouldn't want to recalculate and rerender all other markers every time user location changes.

**Comment by ScreamZ** [comment]
@JiriHoffmann Yes, but how am I supposed to exclude it, I only have one clustered map instance ?

Of course, I want to exclude it and add a specific visual.

Do you have a small example? I might be totally dumb but I don't get how

Thanks :)

**Comment by ScreamZ** [comment]
Nice, thanks for this :-)
